import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
import { PGlite } from '@electric-sql/pglite';
const db = new PGlite();
const root = new URL('../../', import.meta.url);
await db.exec(`create role anon; create role authenticated; create role service_role bypassrls;
create schema auth; create table auth.users(id uuid primary key,raw_user_meta_data jsonb default '{}',deleted_at timestamptz,banned_until timestamptz);
create function auth.uid() returns uuid language sql stable as $$select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid$$;
grant usage on schema auth to authenticated,service_role; grant select on auth.users to service_role; grant execute on function auth.uid() to authenticated;`);
for (const name of ['0001_screening_schema.sql','0002_rls_and_auth_helpers.sql','0003_harden_function_privileges.sql','0007_harden_screening_and_membership_writes.sql','0008_avoid_membership_policy_recursion.sql','20260925202332_advisor_access_and_usage.sql']) {
  const sql = await readFile(new URL(`supabase/migrations/${name}`,root),'utf8');
  await db.exec(sql.replace('create extension if not exists pgcrypto;',''));
}
await db.exec(`grant select on public.screening_runs,public.screening_reports,public.organization_members to service_role;
grant usage on schema public to authenticated,service_role,anon;`);
const uuid = n => `00000000-0000-0000-0000-${String(n).padStart(12,'0')}`;
const user=uuid(1), other=uuid(2), org=uuid(10), otherOrg=uuid(11), run=uuid(20), otherRun=uuid(21), rubric=uuid(30);
await db.query(`insert into auth.users(id) values ($1),($2),($3)`,[user,other,uuid(3)]);
await db.query(`insert into organizations(id,name,organization_type) values ($1,'A','business'),($2,'B','nonprofit')`,[org,otherOrg]);
await db.query(`insert into organization_members(organization_id,user_id,role) values ($1,$2,'owner'),($3,$4,'owner')`,[org,user,otherOrg,other]);
await db.query(`insert into organization_members(organization_id,user_id,role) values ($1,$2,'owner')`,[org,uuid(3)]);
await db.query(`insert into rubric_versions(id,name,version,screening_type) values ($1,'v1','v1','business')`,[rubric]);
await db.query(`insert into screening_runs(id,organization_id,rubric_version_id,screening_type,status) values ($1,$2,$5,'business','complete'),($3,$4,$5,'nonprofit','complete')`,[run,org,otherRun,otherOrg,rubric]);
await db.query(`insert into screening_reports(screening_run_id,total_score) values ($1,73),($2,62)`,[run,otherRun]);
const as = async (role, uid, fn) => { await db.exec(`set role ${role}`); await db.query(`select set_config('request.jwt.claim.sub',$1,false)`,[uid??'']); try { return await fn(); } finally { await db.exec('reset role'); }};
let count=0;
const test=async(name,fn)=>{await fn();count++; console.log(`PASS ${name}`);};
const deny=async(fn,regex=/denied|permission/) => assert.rejects(fn,regex);
const begin=(u=user,r=run,id=uuid(100),tier=0,budget=0,conv=null,q='What is my score?')=>db.query(`select advisor_begin_request($1,$2,$3,$4,$5::smallint,$6,$7) result`,[u,r,id,q,tier,budget,conv]).then(r=>r.rows[0].result);
const finish=(id,verification={},tier=0)=>db.query(`select advisor_finish_request($1,$2,'73/100','[]',$3,0,0,0,$4,$5) result`,[user,id,verification,tier?'model':null,tier?'verifier':null]).then(r=>r.rows[0].result);
await test('all five Advisor tables have RLS',async()=>assert.equal((await db.query(`select count(*)::int n from pg_tables where tablename like 'advisor_%' and rowsecurity`)).rows[0].n,5));
await test('missing entitlement denied',()=>as('service_role',null,()=>deny(()=>begin())));
await test('browser cannot forge entitlement',()=>as('authenticated',user,()=>deny(()=>db.query(`insert into advisor_entitlements(organization_id,screening_run_id,payment_provider,payment_reference,payment_event_id,payment_verified_at) values ($1,$2,'stripe','fake','fake',now())`,[org,run]))));
await test('org/run mismatch rejected even for privileged insert',()=>deny(()=>db.query(`insert into advisor_entitlements(organization_id,screening_run_id,payment_provider,payment_reference,payment_event_id,payment_verified_at) values ($1,$2,'stripe','x','x',now())`,[otherOrg,run]),/foreign key/));
await db.query(`insert into advisor_entitlements(organization_id,screening_run_id,status,payment_provider,payment_reference,payment_event_id,payment_verified_at) values ($1,$2,'active','stripe','TEST_ONLY','TEST_ONLY',now()),($3,$4,'active','stripe','TEST_OTHER','TEST_OTHER',now())`,[org,run,otherOrg,otherRun]);
await test('anon cannot call begin RPC',()=>as('anon',null,()=>deny(()=>begin())));
await test('authenticated caller cannot spoof a service RPC user',()=>as('authenticated',other,()=>deny(()=>begin())));
await test('cross organization denied',()=>as('service_role',null,()=>deny(()=>begin(other,run))));
let first;
await test('authorized completed paid report can begin',()=>as('service_role',null,async()=>{first=await begin();assert.equal(first.status,'reserved');assert.equal(first.replayed,false);}));
await test('exact retry is idempotent',()=>as('service_role',null,async()=>{const r=await begin();assert.equal(r.replayed,true);assert.equal(r.conversation_id,first.conversation_id);}));
await test('mutated retry rejected',()=>as('service_role',null,()=>deny(()=>begin(user,run,uuid(100),0,0,null,'different'),/conflict/)));
await test('unauthorized report switch denied',()=>as('service_role',null,()=>deny(()=>begin(other,otherRun,uuid(101),0,0,first.conversation_id))));
await test('owner sees own conversation, other tenant sees none',async()=>{await as('authenticated',user,async()=>assert.equal((await db.query('select * from advisor_conversations')).rows.length,1));await as('authenticated',other,async()=>assert.equal((await db.query('select * from advisor_conversations')).rows.length,0));});
await test('payment provenance not browser readable',()=>as('authenticated',user,()=>deny(()=>db.query('select payment_reference from advisor_entitlements'))));
await test('expired entitlement denied',async()=>{await db.exec(`update advisor_entitlements set starts_at=now()-interval '2 days',expires_at=now()-interval '1 day' where payment_event_id='TEST_ONLY'`);await as('service_role',null,()=>deny(()=>begin()));await db.exec(`update advisor_entitlements set expires_at=null where payment_event_id='TEST_ONLY'`);});
await test('future entitlement denied',async()=>{await db.exec(`update advisor_entitlements set starts_at=now()+interval '1 day' where payment_event_id='TEST_ONLY'`);await as('service_role',null,()=>deny(()=>begin()));await db.exec(`update advisor_entitlements set starts_at=now() where payment_event_id='TEST_ONLY'`);});
await test('revocation checked at completion and retry',async()=>{await db.exec(`update advisor_entitlements set status='revoked',revoked_at=now() where payment_event_id='TEST_ONLY'`);await as('service_role',null,()=>deny(()=>finish(uuid(100))));await as('service_role',null,()=>deny(()=>begin()));await db.exec(`update advisor_entitlements set status='active',revoked_at=null where payment_event_id='TEST_ONLY'`);});
await test('suspended membership denied, historical chat inaccessible',async()=>{await db.query(`update organization_members set status='suspended' where user_id=$1`,[user]);await as('service_role',null,()=>deny(()=>begin()));await as('authenticated',user,async()=>assert.equal((await db.query('select * from advisor_messages')).rows.length,0));await db.query(`update organization_members set status='active' where user_id=$1`,[user]);});
let answer;
await test('deterministic answer persists and finish retry is idempotent',()=>as('service_role',null,async()=>{answer=await finish(uuid(100));assert.equal(await finish(uuid(100)),answer);}));
await test('feedback is owner-bound',()=>as('service_role',null,async()=>{await db.query('select advisor_record_feedback($1,$2,true)',[user,answer]);await deny(()=>db.query('select advisor_record_feedback($1,$2,true)',[other,answer]));}));
await test('strategic answer requires independent verification',()=>as('service_role',null,async()=>{await begin(user,run,uuid(102),2,1000);await deny(()=>finish(uuid(102),{},2),/Verification/);await finish(uuid(102),{status:'verified',independent:true},2);}));
await test('chain-of-thought metadata key rejected',()=>as('service_role',null,async()=>{await begin(user,run,uuid(103));await deny(()=>finish(uuid(103),{reasoning:'secret'}),/Verification/);}));
await test('token cap enforced',()=>as('service_role',null,()=>deny(()=>begin(user,run,uuid(104),3,24001),/Invalid/)));
await test('rolling rate cap cannot be bypassed with new request IDs',()=>as('service_role',null,async()=>{for (let i=110;i<113;i++)await begin(user,run,uuid(i));await deny(()=>begin(user,run,uuid(113)),/budget exceeded/);}));
await test('no Advisor mutation changes canonical score',async()=>assert.equal((await db.query('select total_score from screening_reports where screening_run_id=$1',[run])).rows[0].total_score,'73.00'));
console.log(`${count} schema assertions passed. Local PGlite only; live/parallel Postgres release tests still required.`);
await db.close();
